"""Loadout: writes the selected skills to an output file or directory."""

from __future__ import annotations

import shutil
from pathlib import Path

from agent_maintenance.core.models import LoadoutResult

_CONTEXT_TEMPLATE = """\
# Loadout: {task}

> Generated by agent-maintenance — top {count} skill(s) selected for this task.

---

{skill_sections}
"""

_SKILL_SECTION_TEMPLATE = """\
## {name}

{description}

{content}
"""


class LoadoutWriter:
    """Writes a LoadoutResult to a CONTEXT.md file or a loadout/ directory."""

    def write_context_md(self, result: LoadoutResult, output_path: Path) -> Path:
        """Write all selected skills into a single aggregated CONTEXT.md file."""
        output_path.parent.mkdir(parents=True, exist_ok=True)

        skill_sections = "\n---\n\n".join(
            _SKILL_SECTION_TEMPLATE.format(
                name=skill.metadata.name,
                description=skill.metadata.description or "_No description_",
                content=skill.content,
            )
            for skill in result.selected_skills
        )

        text = _CONTEXT_TEMPLATE.format(
            task=result.task_description,
            count=len(result.selected_skills),
            skill_sections=skill_sections,
        )

        output_path.write_text(text, encoding="utf-8")
        return output_path

    def write_loadout_dir(self, result: LoadoutResult, output_dir: Path) -> Path:
        """Copy each selected skill into a dedicated loadout directory.

        - Legacy flat skills are copied as a single ``.md`` file.
        - Folder skills are copied as their whole folder (scripts, references,
          and assets included), keyed by the folder name — never flattened to a
          bare ``SKILL.md`` that would collide with other folder skills.

        Name collisions are resolved with a numeric suffix.
        """
        output_dir.mkdir(parents=True, exist_ok=True)

        for skill in result.selected_skills:
            source = skill.archive_target  # folder for folder skills, else the .md file
            if not source or not source.exists():
                continue

            if source.is_dir():
                dest = self._unique_dest(output_dir, source.name)
                shutil.copytree(source, dest)
            else:
                dest = self._unique_dest(output_dir, source.name)
                dest.write_bytes(source.read_bytes())

        return output_dir

    @staticmethod
    def _unique_dest(directory: Path, name: str) -> Path:
        """Return a destination path in ``directory`` that does not yet exist."""
        dest = directory / name
        if not dest.exists():
            return dest

        stem = Path(name).stem
        suffix = Path(name).suffix
        counter = 1
        while dest.exists():
            dest = directory / f"{stem}_{counter}{suffix}"
            counter += 1
        return dest
