"""Loadout: writes the selected skills to an output file or directory."""

from __future__ import annotations

from pathlib import Path

from agent_maintenance.core.models import LoadoutResult

_CONTEXT_TEMPLATE = """\
# Loadout: {task}

> Generated by agent-maintenance — top {count} skill(s) selected for this task.

---

{skill_sections}
"""

_SKILL_SECTION_TEMPLATE = """\
## {name}

{description}

{content}
"""


class LoadoutWriter:
    """Writes a LoadoutResult to a CONTEXT.md file or a loadout/ directory."""

    def write_context_md(self, result: LoadoutResult, output_path: Path) -> Path:
        """Write all selected skills into a single aggregated CONTEXT.md file."""
        output_path.parent.mkdir(parents=True, exist_ok=True)

        skill_sections = "\n---\n\n".join(
            _SKILL_SECTION_TEMPLATE.format(
                name=skill.metadata.name,
                description=skill.metadata.description or "_No description_",
                content=skill.content,
            )
            for skill in result.selected_skills
        )

        text = _CONTEXT_TEMPLATE.format(
            task=result.task_description,
            count=len(result.selected_skills),
            skill_sections=skill_sections,
        )

        output_path.write_text(text, encoding="utf-8")
        return output_path

    def write_loadout_dir(self, result: LoadoutResult, output_dir: Path) -> Path:
        """Copy each selected skill into a dedicated loadout directory."""
        output_dir.mkdir(parents=True, exist_ok=True)

        for skill in result.selected_skills:
            if skill.source_path and skill.source_path.exists():
                dest = output_dir / skill.source_path.name
                dest.write_bytes(skill.source_path.read_bytes())

        return output_dir
